import os
import sys
import json
import unittest
from pathlib import Path

# Add parent directory to sys.path to import existing modules
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / 'alert-engine'))
sys.path.insert(0, str(REPO_ROOT / 'gis-engine'))

from cap_generator import build_cap_alert_payload, generate_cap_json
from i18n_templates import I18N_TEMPLATES
from evacuation_router import EvacuationRouter
from road_network import RoadNetworkGraph

class TestMobileAppIntegration(unittest.TestCase):
    """
    Validates end-to-end integration between Module 5 (Flutter Mobile App)
    and the backend modules (Module 0 Sync, Module 3 Alert, Module 4 GIS).
    """

    def setUp(self):
        self.mobile_dir = REPO_ROOT / 'mobile-app'

    def test_01_flutter_project_structure(self):
        """Verifies that all required Clean Architecture files and folders exist in mobile-app."""
        required_files = [
            'pubspec.yaml',
            'README.md',
            'lib/main.dart',
            'lib/core/constants/api_endpoints.dart',
            'lib/core/constants/app_colors.dart',
            'lib/core/theme/app_theme.dart',
            'lib/core/i18n/dialect_translations.dart',
            'lib/domain/models/field_report.dart',
            'lib/domain/models/emergency_alert.dart',
            'lib/domain/models/evacuation_path.dart',
            'lib/data/models/field_report_model.dart',
            'lib/data/models/alert_model.dart',
            'lib/data/models/evacuation_route_model.dart',
            'lib/data/services/local_database_service.dart',
            'lib/data/services/api_client.dart',
            'lib/data/services/gps_service.dart',
            'lib/data/services/audio_alarm_service.dart',
            'lib/data/repositories/field_report_repository.dart',
            'lib/data/repositories/alert_repository.dart',
            'lib/data/repositories/evacuation_repository.dart',
            'lib/ui/shared_widgets/offline_sync_banner.dart',
            'lib/ui/shared_widgets/status_badge.dart',
            'lib/ui/shared_widgets/custom_button.dart',
            'lib/ui/features/home/home_screen.dart',
            'lib/ui/features/home/home_view_model.dart',
            'lib/ui/features/report/new_report_screen.dart',
            'lib/ui/features/report/new_report_view_model.dart',
            'lib/ui/features/sos/sos_screen.dart',
            'lib/ui/features/sos/sos_view_model.dart',
            'lib/ui/features/evacuation/evacuation_map_screen.dart',
            'lib/ui/features/evacuation/evacuation_view_model.dart',
            'lib/ui/features/alerts/alerts_screen.dart',
            'lib/ui/features/alerts/alerts_view_model.dart',
            'test/unit_test.dart',
        ]

        for rel_path in required_files:
            target = self.mobile_dir / rel_path
            self.assertTrue(target.exists(), f"Missing required Flutter file: {rel_path}")

    def test_02_field_report_schema_contract(self):
        """Verifies that Flutter FieldReportModel schema maps to Module 0 SQLite/Cloud Gateway schema."""
        # Simulated payload generated by Flutter FieldReportModel.toJson()
        flutter_payload = {
            "client_id": "c7a8b9e1-2345-4a6b-8c9d-0123456789ab",
            "reporter_name": "Tashi Dorjee",
            "reporter_role": "Field Scout",
            "reporter_phone": "+91 98320 12345",
            "hazard_type": "Tension Crack",
            "severity": "HIGH",
            "state": "Sikkim",
            "district": "East Sikkim",
            "latitude": 27.3250,
            "longitude": 88.6120,
            "location_description": "NH-10 km 22 Ranipool culvert",
            "tension_crack_width_cm": 14.5,
            "road_status": "BLOCKED",
            "image_url": None,
            "notes": "Slope deformation observed",
            "language": "en",
            "local_created_at": "2026-09-11T05:30:00.000Z"
        }

        # Check expected Module 0 fields
        required_fields = ['client_id', 'reporter_name', 'hazard_type', 'severity', 'state', 'district', 'latitude', 'longitude', 'local_created_at']
        for field in required_fields:
            self.assertIn(field, flutter_payload)
            self.assertIsNotNone(flutter_payload[field])

        self.assertIn(flutter_payload['severity'], ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])

    def test_03_cap_alert_compatibility_with_module_3(self):
        """Verifies that Module 3's OASIS CAP alert can be ingested by Flutter AlertModel."""
        alert_data = build_cap_alert_payload(
            zone_code='SKM_NH10_RANIPOOL',
            station_name='Ranipool Highway Cut Slope',
            state='Sikkim',
            district='East Sikkim',
            latitude=27.2950,
            longitude=88.5850,
            lsi_score=0.94,
            factor_of_safety=0.82,
            rainfall_mm=88.0,
            pore_pressure_kpa=48.5,
            languages=['en']
        )
        cap_wrapper = generate_cap_json(alert_data)
        cap_json = cap_wrapper['alert']
        self.assertIn('identifier', cap_json)
        self.assertIn('info_blocks', cap_json)
        info = cap_json['info_blocks'][0]
        self.assertEqual(info['severity'], 'Extreme')

        # Test field presence for Flutter AlertModel.fromJson()
        headline = info['headline']
        description = info['description']
        instruction = info['instruction']
        self.assertTrue(len(headline) > 0)
        self.assertTrue(len(description) > 0)
        self.assertTrue(len(instruction) > 0)

    def test_04_evacuation_route_compatibility_with_module_4(self):
        """Verifies that Module 4's safe bypass route can be ingested by Flutter EvacuationRouteModel."""
        router = EvacuationRouter()
        hazards = [{
            'lat': 27.3050,
            'lng': 88.5880,
            'threat_radius_km': 1.8,
            'label': 'Ranipool Active Debris Flow'
        }]
        route_res = router.compute_safe_route(
            start_id='SKM_32MILE',
            target_shelter_id='SKM_UPPER_MARTAM_SHELTER',
            hazards=hazards
        )

        self.assertTrue(route_res['success'])
        self.assertEqual(route_res['status'], 'SAFE_BYPASS_VERIFIED')

        # Verify attributes expected by Flutter EvacuationRouteModel
        self.assertIn('total_distance_km', route_res)
        self.assertIn('estimated_time_minutes', route_res)
        self.assertIn('polyline_coordinates', route_res)
        self.assertIn('destination_shelter', route_res)

        shelter = route_res['destination_shelter']
        self.assertIn('name', shelter)
        self.assertIn('shelter_capacity', shelter)
        self.assertGreater(shelter['shelter_capacity'], 0)

    def test_05_dialect_coverage(self):
        """Verifies that all 8 NER dialects in Module 3 are mapped in Flutter DialectTranslations."""
        flutter_i18n_path = self.mobile_dir / 'lib' / 'core' / 'i18n' / 'dialect_translations.dart'
        content = flutter_i18n_path.read_text(encoding='utf-8')

        for code in I18N_TEMPLATES.keys():
            self.assertIn(f"'{code}'", content, f"Dialect {code} not mapped in Flutter DialectTranslations")

if __name__ == '__main__':
    unittest.main()
